"""Add UC calculator and LHA rates models

Revision ID: a5785afbb3dc
Revises: 7491686beae0
Create Date: 2026-02-16 19:13:34.020520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5785afbb3dc'
down_revision: Union[str, Sequence[str], None] = '7491686beae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lha_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brma_code', sa.String(length=50), nullable=False),
    sa.Column('brma_name', sa.String(length=255), nullable=False),
    sa.Column('local_authority', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('studio_rate', sa.Float(), nullable=True),
    sa.Column('one_bed_rate', sa.Float(), nullable=False),
    sa.Column('two_bed_rate', sa.Float(), nullable=False),
    sa.Column('three_bed_rate', sa.Float(), nullable=False),
    sa.Column('four_bed_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lha_rates_brma_code'), 'lha_rates', ['brma_code'], unique=False)
    op.create_index(op.f('ix_lha_rates_effective_from'), 'lha_rates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_lha_rates_id'), 'lha_rates', ['id'], unique=False)
    op.create_table('uc_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_reference', sa.String(length=50), nullable=False),
    sa.Column('claimant_type', sa.Enum('SINGLE', 'JOINT', name='claimanttype'), nullable=False),
    sa.Column('claimant_age', sa.Integer(), nullable=False),
    sa.Column('partner_age', sa.Integer(), nullable=True),
    sa.Column('children', sa.JSON(), nullable=True),
    sa.Column('housing_type', sa.Enum('OWNER_OCCUPIER', 'RENTER', 'SOCIAL_HOUSING', name='housingtype'), nullable=False),
    sa.Column('bedrooms_needed', sa.Integer(), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('brma_code', sa.String(length=50), nullable=True),
    sa.Column('monthly_earnings', sa.Float(), nullable=True),
    sa.Column('partner_monthly_earnings', sa.Float(), nullable=True),
    sa.Column('has_work_allowance', sa.Boolean(), nullable=True),
    sa.Column('has_childcare_costs', sa.Boolean(), nullable=True),
    sa.Column('monthly_childcare_costs', sa.Float(), nullable=True),
    sa.Column('has_disability', sa.Boolean(), nullable=True),
    sa.Column('is_carer', sa.Boolean(), nullable=True),
    sa.Column('assessment_month', sa.Date(), nullable=False),
    sa.Column('standard_allowance', sa.Float(), nullable=True),
    sa.Column('housing_element', sa.Float(), nullable=True),
    sa.Column('child_element', sa.Float(), nullable=True),
    sa.Column('childcare_element', sa.Float(), nullable=True),
    sa.Column('disability_element', sa.Float(), nullable=True),
    sa.Column('carer_element', sa.Float(), nullable=True),
    sa.Column('earnings_deduction', sa.Float(), nullable=True),
    sa.Column('total_entitlement', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['brma_code'], ['lha_rates.brma_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uc_claims_claim_reference'), 'uc_claims', ['claim_reference'], unique=True)
    op.create_index(op.f('ix_uc_claims_id'), 'uc_claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uc_claims_id'), table_name='uc_claims')
    op.drop_index(op.f('ix_uc_claims_claim_reference'), table_name='uc_claims')
    op.drop_table('uc_claims')
    op.drop_index(op.f('ix_lha_rates_id'), table_name='lha_rates')
    op.drop_index(op.f('ix_lha_rates_effective_from'), table_name='lha_rates')
    op.drop_index(op.f('ix_lha_rates_brma_code'), table_name='lha_rates')
    op.drop_table('lha_rates')
    # ### end Alembic commands ###
